import '../models/book.dart';
import '../models/user_book.dart';
import '../models/wishlist_book.dart';
import '../models/listing.dart';
import '../models/chat_message.dart';

class SampleData {
  static List<Listing> getInitialListings() {
    return [
      Listing(
        id: 'list_1',
        book: const Book(
          id: 'b_1',
          isbn: '9788308064177',
          title: 'Bieguni',
          author: 'Olga Tokarczuk',
          description:
              'Laureatka Literackiej Nagrody Nobla. Jedna z najważniejszych polskich powieści XXI wieku, opowieść o nomadyzmie, podróży i ludzkim ciele.',
          coverUrl: 'https://covers.openlibrary.org/b/isbn/9788308064177-L.jpg',
          publisher: 'Wydawnictwo Literackie',
          publishYear: 2018,
          pageCount: 456,
          categories: ['Literatura piękna', 'Proza polska'],
          condition: BookCondition.asNew,
        ),
        sellerId: 'seller_anna',
        sellerName: 'Anna Kowalska',
        sellerRating: 4.95,
        completedExchangesCount: 14,
        city: 'Warszawa',
        district: 'Mokotów (metro Pole Mokotowskie)',
        latitude: 52.2090,
        longitude: 21.0080, // ~2.3 km from downtown Warszawa
        type: ListingType.both,
        price: 28.0,
        exchangePreferences:
            'Chętnie wymienię na Murakamiego, Hessego lub dobry reportaż z Czarnego.',
        createdAt: DateTime.now().subtract(const Duration(hours: 2)),
      ),
      Listing(
        id: 'list_2',
        book: const Book(
          id: 'b_2',
          isbn: '9788375780635',
          title: 'Ostatnie życzenie (Wiedźmin)',
          author: 'Andrzej Sapkowski',
          description:
              'Pierwszy tom sagi o wiedźminie Geralcie z Rivii. Zawiera kultowe opowiadania wprowadzające do świata Sapkowskiego.',
          coverUrl: 'https://covers.openlibrary.org/b/isbn/9788375780635-L.jpg',
          publisher: 'SuperNOWA',
          publishYear: 2014,
          pageCount: 332,
          categories: ['Fantastyka', 'Fantasy'],
          condition: BookCondition.veryGood,
        ),
        sellerId: 'seller_michal',
        sellerName: 'Michał Wiśniewski',
        sellerRating: 4.88,
        completedExchangesCount: 9,
        city: 'Warszawa',
        district: 'Ochota (pl. Narutowicza)',
        latitude: 52.2170,
        longitude: 20.9850, // ~2.2 km from downtown
        type: ListingType.exchange,
        price: null,
        exchangePreferences:
            'Wymienię tylko na fantastykę: Sanderson, Erikson lub Dukaj.',
        createdAt: DateTime.now().subtract(const Duration(hours: 6)),
      ),
      Listing(
        id: 'list_3',
        book: const Book(
          id: 'b_3',
          isbn: '9788375155280',
          title: 'Kasacja',
          author: 'Remigiusz Mróz',
          description:
              'Pierwsza część bestsellerowej serii z mecenas Joanną Chyłką i Kordianem Oryńskim. Prawniczy thriller trzymający w napięciu.',
          coverUrl: 'https://covers.openlibrary.org/b/isbn/9788375155280-L.jpg',
          publisher: 'Czwarta Strona',
          publishYear: 2019,
          pageCount: 496,
          categories: ['Kryminał', 'Sensacja'],
          condition: BookCondition.good,
        ),
        sellerId: 'seller_kasia',
        sellerName: 'Kasia Zielińska',
        sellerRating: 5.0,
        completedExchangesCount: 22,
        city: 'Warszawa',
        district: 'Śródmieście (okolice Politechniki)',
        latitude: 52.2215,
        longitude: 21.0105, // ~0.9 km from downtown (very close!)
        type: ListingType.both,
        price: 18.0,
        exchangePreferences:
            'Wymiana na inny kryminał (np. Chmielarz, Bonda) albo odbiór osobisty.',
        createdAt: DateTime.now().subtract(const Duration(hours: 14)),
      ),
      Listing(
        id: 'list_4',
        book: const Book(
          id: 'b_4',
          isbn: '9788328700581',
          title: '1984',
          author: 'George Orwell',
          description:
              'Wielki Brat patrzy. Ponadczasowe arcydzieło literatury antyutopijnej o totalitaryzmie, cenzurze i nowomowie.',
          coverUrl: 'https://covers.openlibrary.org/b/isbn/9788328700581-L.jpg',
          publisher: 'Muza',
          publishYear: 2021,
          pageCount: 360,
          categories: ['Klasyka', 'Dystopia'],
          condition: BookCondition.asNew,
        ),
        sellerId: 'seller_tomek',
        sellerName: 'Tomasz Lewandowski',
        sellerRating: 4.75,
        completedExchangesCount: 5,
        city: 'Warszawa',
        district: 'Praga Północ (Dworzec Wileński)',
        latitude: 52.2540,
        longitude: 21.0360, // ~3.5 km from downtown
        type: ListingType.sale,
        price: 22.0,
        exchangePreferences: 'Możliwa też wymiana na Huxleya (Nowy wspaniały świat).',
        createdAt: DateTime.now().subtract(const Duration(days: 1)),
      ),
      Listing(
        id: 'list_5',
        book: const Book(
          id: 'b_5',
          isbn: '9788308075302',
          title: 'Solaris',
          author: 'Stanisław Lem',
          description:
              'Najsłynniejsza powieść Lema. Spotkanie ludzkości z żywym, myślącym oceanem i badanie granic ludzkiego poznania.',
          coverUrl: 'https://covers.openlibrary.org/b/isbn/9788308075302-L.jpg',
          publisher: 'Wydawnictwo Literackie',
          publishYear: 2021,
          pageCount: 264,
          categories: ['Science Fiction', 'Filozofia'],
          condition: BookCondition.asNew,
        ),
        sellerId: 'seller_wojtek',
        sellerName: 'Wojciech Szymański',
        sellerRating: 4.9,
        completedExchangesCount: 17,
        city: 'Warszawa',
        district: 'Ursynów (metro Kabaty)',
        latitude: 52.1310,
        longitude: 21.0650, // ~11.5 km from downtown (Outside 5 km radius)
        type: ListingType.both,
        price: 25.0,
        exchangePreferences: 'Szukam klasyki Sci-Fi: Dick, Asimov, Strugaccy.',
        createdAt: DateTime.now().subtract(const Duration(days: 2)),
      ),
      Listing(
        id: 'list_6',
        book: const Book(
          id: 'b_6',
          isbn: '9788381162470',
          title: 'Lśnienie',
          author: 'Stephen King',
          description:
              'Hotel Panorama zimą odcięty od świata. Porażające studium szaleństwa i nadprzyrodzonych zjawisk.',
          coverUrl: 'https://covers.openlibrary.org/b/isbn/9788381162470-L.jpg',
          publisher: 'Prószyński i S-ka',
          publishYear: 2020,
          pageCount: 544,
          categories: ['Horror', 'Thriller'],
          condition: BookCondition.veryGood,
        ),
        sellerId: 'seller_magda',
        sellerName: 'Magda Nowicka',
        sellerRating: 4.95,
        completedExchangesCount: 31,
        city: 'Kraków',
        district: 'Stare Miasto / Kazimierz',
        latitude: 50.0520,
        longitude: 19.9450,
        type: ListingType.both,
        price: 32.0,
        exchangePreferences: 'Wymienię na inne książki Kinga lub Mastertona.',
        createdAt: DateTime.now().subtract(const Duration(days: 1)),
      ),
      Listing(
        id: 'list_7',
        book: const Book(
          id: 'b_7',
          isbn: '9788324404551',
          title: 'Hobbit, czyli tam i z powrotem',
          author: 'J.R.R. Tolkien',
          description:
              'Niebezpieczna wyprawa Bilba Bagginsa i krasnoludów ku Samotnej Górze strzeżonej przez smoka Smauga.',
          coverUrl: 'https://covers.openlibrary.org/b/isbn/9788324404551-L.jpg',
          publisher: 'Iskry',
          publishYear: 2017,
          pageCount: 316,
          categories: ['Fantastyka', 'Młodzieżowa'],
          condition: BookCondition.asNew,
        ),
        sellerId: 'seller_piotr',
        sellerName: 'Piotr Kaczmarek',
        sellerRating: 4.8,
        completedExchangesCount: 6,
        city: 'Wrocław',
        district: 'Śródmieście / Ołbin',
        latitude: 51.1180,
        longitude: 17.0520,
        type: ListingType.exchange,
        price: null,
        exchangePreferences: 'Chętnie wymienię na Władcę Pierścieni tom 2 lub 3.',
        createdAt: DateTime.now().subtract(const Duration(days: 3)),
      ),
      Listing(
        id: 'list_8',
        book: const Book(
          id: 'b_8',
          isbn: '9788308047972',
          title: 'Lód',
          author: 'Jacek Dukaj',
          description:
              'Monumentalna powieść o alternatywnej historii, w której I wojna światowa nie wybuchła, a Królestwo Polskie zamroził lód z meteorytu.',
          coverUrl: 'https://covers.openlibrary.org/b/isbn/9788308047972-L.jpg',
          publisher: 'Wydawnictwo Literackie',
          publishYear: 2016,
          pageCount: 1056,
          categories: ['Fantastyka', 'Sci-Fi'],
          condition: BookCondition.good,
        ),
        sellerId: 'seller_kamil',
        sellerName: 'Kamil Wójcik',
        sellerRating: 4.85,
        completedExchangesCount: 12,
        city: 'Poznań',
        district: 'Jeżyce',
        latitude: 52.4130,
        longitude: 16.9070,
        type: ListingType.both,
        price: 45.0,
        exchangePreferences: 'Wymiana na inne tomy Dukaja lub Lema.',
        createdAt: DateTime.now().subtract(const Duration(days: 4)),
      ),
    ];
  }

  static List<UserBook> getInitialUserBooks() {
    return [
      UserBook(
        id: 'ub_1',
        book: const Book(
          id: 'my_b_1',
          isbn: '9788308075302',
          title: 'Solaris',
          author: 'Stanisław Lem',
          description: 'Stan idealny, raz czytana, bez zagięć.',
          coverUrl: 'https://covers.openlibrary.org/b/isbn/9788308075302-L.jpg',
          publisher: 'Wydawnictwo Literackie',
          publishYear: 2021,
          pageCount: 264,
          categories: ['Science Fiction'],
          condition: BookCondition.asNew,
        ),
        type: UserBookType.both,
        price: 25.0,
        isListed: true,
        preferredExchangeGenres: 'Kryminał, Thriller, Klasyka',
      ),
      UserBook(
        id: 'ub_2',
        book: const Book(
          id: 'my_b_2',
          isbn: '9788375155280',
          title: 'Kasacja',
          author: 'Remigiusz Mróz',
          description: 'Dobry stan, drobne ślady czytania na grzbiecie.',
          coverUrl: 'https://covers.openlibrary.org/b/isbn/9788375155280-L.jpg',
          publisher: 'Czwarta Strona',
          publishYear: 2019,
          pageCount: 496,
          categories: ['Kryminał'],
          condition: BookCondition.good,
        ),
        type: UserBookType.forExchange,
        price: null,
        isListed: false,
        preferredExchangeGenres: 'Fantastyka, Dukaj, Sapkowski',
      ),
    ];
  }

  static List<WishlistBook> getInitialWishlist() {
    return [
      WishlistBook(
        id: 'w_1',
        isbn: '9788328700581',
        title: '1984',
        author: 'George Orwell',
        coverUrl: 'https://covers.openlibrary.org/b/isbn/9788328700581-L.jpg',
        notes: 'Szukam wydania ze współczesnym przekładem, stan min. dobry.',
        maxBudget: 25.0,
        willingToExchange: true,
        priority: WishlistPriority.high,
      ),
      WishlistBook(
        id: 'w_2',
        isbn: '9788381162470',
        title: 'Lśnienie',
        author: 'Stephen King',
        coverUrl: 'https://covers.openlibrary.org/b/isbn/9788381162470-L.jpg',
        notes: 'Chętnie wymienię na inną książkę z mojej półki.',
        maxBudget: 35.0,
        willingToExchange: true,
        priority: WishlistPriority.medium,
      ),
      WishlistBook(
        id: 'w_3',
        isbn: '9788324404551',
        title: 'Hobbit',
        author: 'J.R.R. Tolkien',
        coverUrl: 'https://covers.openlibrary.org/b/isbn/9788324404551-L.jpg',
        notes: 'Dla młodszego rodzeństwa, ilustrowane wydanie mile widziane.',
        maxBudget: 30.0,
        willingToExchange: true,
        priority: WishlistPriority.low,
      ),
    ];
  }

  static List<ChatConversation> getInitialConversations() {
    return [
      ChatConversation(
        id: 'conv_1',
        listingId: 'list_1',
        bookTitle: 'Bieguni',
        bookAuthor: 'Olga Tokarczuk',
        bookCoverUrl: 'https://covers.openlibrary.org/b/isbn/9788308064177-L.jpg',
        otherUserId: 'seller_anna',
        otherUserName: 'Anna Kowalska',
        otherUserCity: 'Warszawa, Mokotów',
        messages: [
          ChatMessage(
            id: 'm_1',
            senderId: 'current_user',
            senderName: 'Ja',
            text: 'Dzień dobry! Czy ta książka jest nadal do wymiany?',
            timestamp: DateTime.now().subtract(const Duration(hours: 3)),
            isMe: true,
          ),
          ChatMessage(
            id: 'm_2',
            senderId: 'seller_anna',
            senderName: 'Anna Kowalska',
            text:
                'Cześć! Tak, Bieguni są dostępni. Jesteś z Warszawy? Gdzie najbardziej pasowałoby Ci się spotkać?',
            timestamp: DateTime.now().subtract(const Duration(hours: 2, minutes: 40)),
            isMe: false,
          ),
          ChatMessage(
            id: 'm_3',
            senderId: 'current_user',
            senderName: 'Ja',
            text:
                'Pracuję przy Rondzie Daszyńskiego, ale mogę podjechać na stację Metro Pole Mokotowskie!',
            timestamp: DateTime.now().subtract(const Duration(hours: 2, minutes: 15)),
            isMe: true,
            proposal: ExchangeProposal(
              id: 'prop_1',
              offeredBookTitle: 'Solaris - Stanisław Lem',
              offeredBookCover:
                  'https://covers.openlibrary.org/b/isbn/9788308075302-L.jpg',
              requestedBookTitle: 'Bieguni - Olga Tokarczuk',
              proposedLocation: 'Metro Pole Mokotowskie (przy kawiarni)',
              status: ProposalStatus.accepted,
            ),
          ),
          ChatMessage(
            id: 'm_4',
            senderId: 'seller_anna',
            senderName: 'Anna Kowalska',
            text:
                'Świetnie! Lem bardzo mi odpowiada. Pasuje mi jutro o 17:30. Nie musimy wymieniać się telefonami, napiszemy tutaj jak będziemy na miejscu.',
            timestamp: DateTime.now().subtract(const Duration(hours: 1, minutes: 50)),
            isMe: false,
          ),
        ],
        updatedAt: DateTime.now().subtract(const Duration(hours: 1, minutes: 50)),
        unreadCount: 0,
      ),
      ChatConversation(
        id: 'conv_2',
        listingId: 'list_3',
        bookTitle: 'Kasacja',
        bookAuthor: 'Remigiusz Mróz',
        bookCoverUrl: 'https://covers.openlibrary.org/b/isbn/9788375155280-L.jpg',
        otherUserId: 'seller_kasia',
        otherUserName: 'Kasia Zielińska',
        otherUserCity: 'Warszawa, Śródmieście',
        messages: [
          ChatMessage(
            id: 'm_20',
            senderId: 'seller_kasia',
            senderName: 'Kasia Zielińska',
            text: 'Cześć! Widziałam, że Kasacja Cię interesuje. Odbiór w Śródmieściu.',
            timestamp: DateTime.now().subtract(const Duration(minutes: 45)),
            isMe: false,
          ),
        ],
        updatedAt: DateTime.now().subtract(const Duration(minutes: 45)),
        unreadCount: 1,
      ),
    ];
  }
}
